version: "3.9"
services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        network_mode: host
        user: "1000:1000"
        command:
            - '--web.enable-lifecycle'
            - '--web.enable-admin-api' 
            - '--web.listen-address=:9090'
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--storage.tsdb.path=/prometheus'
        volumes:
            - ./prometheus_data/:/prometheus
            - ./config/:/etc/prometheus/
        restart: always

